### ISSUE TITLE
Addition of a step by step documentation tutorial

### ISSUE THREAD

**Issue by Shreyas-SAS** [atapas/fork-me#120]
**Is your feature request related to a problem? Please describe.**
This repository features a video tutorial from the owner but it could be good if there could also be a follow-up documentation tutorial with images that could help the learners implement and understand fork better.

**Describe the solution you'd like**
I would Like to create a documented tutorial aided with screenshots at each step to help learners grasp the concept well not just from a video source but even a documented tutorial that can preferably made with a google slides ppt for stepwise transition.

**Describe alternatives you've considered**
if google slides is not good then a markdown/pdf would be an alternative to the step by step follow up.

**Additional context**
If allowed, I would like to complete this issue under **HACTOBERFEST'22**

**Comment by atapas** [comment]
Thank you @Shreyas-SAS  

I'm on vacation, will look into it from Wednesday, 5th Oct. Keep going, keep contributing 👍

**Comment by Shreyas-SAS** [comment]
yes thanks @atapas, will complete the issue till the time, please add the Hactoberfest tag on the issue so that it can be counted in.

**Comment by atapas** [comment]
@Shreyas-SAS What's your plan in publishing it?

**Comment by Shreyas-SAS** [comment]
Basically I will first explain what exactly a fork is in 1st 2 slides, then I would display how forking can be done using git bash CLI step by step. Then give a shorter and sweeter way by using github. After this at the end I will explain how fork is different from downloading files and give alternate way for file download from parent repo via SSH key or HTTP link. I thought that I would explain the diff. Between SSH and HTTP too.

**Comment by Shreyas-SAS** [comment]
If you have any suggestions I would love to add them in.

**Comment by Shreyas-SAS** [comment]
In the pull request I would just add the link of the google slide in the Readme.md file. If you would like I would send the slides to you first so that you have the ownership and I can add that link here. How should we go about it?

**Comment by atapas** [comment]
> If you have any suggestions I would love to add them in. 

Great, lets publish it as a blog article. I'll share you the link to create a draft shortly.

**Comment by Shreyas-SAS** [comment]
> Great, lets publish it as a blog article. I'll share you the link to create a draft shortly.

blog, I don't think that it would be a good idea, if I am correct we cannot create a specific step by step instruction and it would be much more effective as slides. though we can write it as step 1, step 2 thing but it is not that effective as each step on a new slide with images, but if its necessary to write a blog, I am up for it, just tell if I should write it on my account or yours. thanks

**Comment by atapas** [comment]
> > Great, lets publish it as a blog article. I'll share you the link to create a draft shortly.
> 
> blog, I don't think that it would be a good idea, if I am correct we cannot create a specific step by step instruction and it would be much more effective as slides. though we can write it as step 1, step 2 thing but it is not that effective as each step on a new slide with images, but if its necessary to write a blog, I am up for it, just tell if I should write it on my account or yours. thanks

Not really, we can do step by step instruction in blog too... Btw, you can come up with the slides first and then let me give you a few pointers to convert that into blog. We can persist both.

For the publication, we can publish it here: https://hashnode.com/teams/invite/671fa63b-fda9-4654-9afb-0c0de2889989

**Comment by Shreyas-SAS** [comment]
> Not really, we can do step by step instruction in blog too... Btw, you can come up with the slides first and then let me give you a few pointers to convert that into blog. We can persist both.
> 
> For the publication, we can publish it here: https://hashnode.com/teams/invite/671fa63b-fda9-4654-9afb-0c0de2889989

Yeah no worries, I will write a blog for it instead. Will do it using the above link and update you. I am still left with searching for free to use images so will update you by tomorrow night. Thanks.

**Comment by kkartik07** [comment]
Hi @atapas. Please can you explain about what's the issue and what we can do?
Thanks.

**Comment by atapas** [comment]
@Shreyas-SAS is doing a no-code contribution. Is it done?

**Comment by Shreyas-SAS** [comment]
> @Shreyas-SAS is doing a no-code contribution. Is it done?

Actually I would do this contribution after hactoberfest. I forgot to mention that here i guess.

**Comment by Shreyas-SAS** [comment]
@kkartik07 would you like to take this issue up?

**Comment by Shreyas-SAS** [comment]
> I was going to complete this issue first but was invited to contribute to some other repo and i saw that PRs were not being accepted on other of @atapas owned repos so lost my confidence. Time too is a key at getting the tshirt for hactoberfest  so tried contributing to other repos.

Please don't take it personally @atapas . I know that its difficult to maintain repos single handedly but we too wish to be rewarded for our work. If @kkartik07 doesn't complete it then I would complete the issue after hactoberfest. Till then it can be open or closed. Your wish.

**Comment by Shreyas-SAS** [comment]
If you wish to close it, feel free to do it. I have noted down the contribution in my calendar for next month so will revisit this again if I complete all 4 PRs or hactoberfest ends before it. I am at 2 accepted and 3 pending so it would be soon I believe. Thanks for understanding @atapas

**Comment by Aniketmishra0** [comment]
Hello Sir,
Can You assign this issue to me?

**Comment by gunjany** [comment]
Step-by-step process can be found here - https://github.com/firstcontributions/first-contributions
