### ISSUE TITLE
Added a new readme file.

### ISSUE THREAD

**Issue by vbsmbb** [atapas/fork-me#430]
I added a new README.md file in vbsmbb/README.md

I would like to be added as a contributor to this project.

I've thought about not asking for a PULL request, but I did it anyway.

**Comment by atapas** [comment]
If your PR is merged, you will be automatically added here.

![image](https://user-images.githubusercontent.com/3633137/219563300-8002ad9e-627a-4082-a213-2d018785d429.png)
